### ISSUE TITLE
Can't extract from DDR files

### ISSUE THREAD

**Issue by Wanny** [SaxxonPike/RhythmCodex#1]
(whee 1st issue)

I tried extracting the contents of GAME.DAT from Solo2000 and I got this output:

```
RhythmCodex 0.0.1
Using Info log level.
Executing ddr extract-573-flash.
[info]   Resolving input files.
[error]  Module 3695 was requested, but not found.
[warn]   An error occurred and the application cannot continue.
```

I'm using the NetCoreApp3.0 CLI version.

**Comment by Wanny** [comment]
With Euromix 2 it said Module 1 instead of 3695...

**Comment by SaxxonPike** [comment]
It seems to be reading garbage data in the Solo2000 case, and in EM2's case you will need to specify both GAME and CARD files on the command line.
